export const GET_DOGS= 'GET_DOGS'
export const GET_TEMPERAMENTS= 'GET_TEMPERAMENTS'
export const DETAIL= 'DETAIL'
export const SEARCH= 'SEARCH'
export const PAGINATE= 'PAGINATE'
export const ORDEN= 'ORDEN'
export const FILTER= 'FILTER'
export const FILTERER= 'FILTERER'